/**
 * sessions.js — opaque bearer tokens in an httpOnly cookie.
 *
 * The token is 32 random bytes, and it is the entire proof of identity: generated by
 * the CSPRNG, never derived from the user, and never stored. The sessions table keeps
 * sha256(token) and nothing else, so a copy of that table is not a set of usable
 * credentials, and there is no key-management problem to get wrong.
 *
 * sha256 rather than scrypt is the right hash here, and the opposite of the choice for
 * passwords: a password is short, guessable and reused, while this token is 256 bits
 * of entropy that no one will ever type. There is nothing to slow down.
 */
'use strict';

const crypto = require('node:crypto');

const TOKEN_BYTES = 32;
const COOKIE_NAME = 'te_session';

/** The stored form of a token. One-way: the plaintext exists only in the cookie. */
function hashToken(token) {
  return crypto.createHash('sha256').update(token).digest('hex');
}

/**
 * Mint a session. The returned `token` goes to the client exactly once; `tokenHash` is
 * what the database gets.
 * @returns {{token: string, tokenHash: string, createdAt: number, expiresAt: number}}
 */
function createSession(ttlMs, now = Date.now()) {
  const token = crypto.randomBytes(TOKEN_BYTES).toString('base64url');
  return { token, tokenHash: hashToken(token), createdAt: now, expiresAt: now + ttlMs };
}

/**
 * The Set-Cookie value for a live session.
 *
 * HttpOnly: the client's own JS cannot read it, so XSS cannot exfiltrate a session.
 * SameSite=Lax: this is the CSRF control. The API is same-origin and every state change
 * is a POST, and Lax withholds cookies from cross-site POSTs — which is why there is no
 * CSRF token here to keep in sync with each form.
 * No Domain: a host-only cookie cannot be leaked to a sibling subdomain.
 */
function sessionCookie(token, { sessionTtlMs, secureCookies }) {
  const attrs = [
    `${COOKIE_NAME}=${token}`,
    'Path=/',
    'HttpOnly',
    'SameSite=Lax',
    `Max-Age=${Math.floor(sessionTtlMs / 1000)}`
  ];
  if (secureCookies) attrs.push('Secure');
  return attrs.join('; ');
}

/**
 * The Set-Cookie value that removes the cookie. Max-Age=0 rather than an empty value,
 * because a browser treats the two differently: an empty value is a cookie that is
 * still sent, an expired one is gone.
 */
function expiredCookie({ secureCookies }) {
  const attrs = [`${COOKIE_NAME}=`, 'Path=/', 'HttpOnly', 'SameSite=Lax', 'Max-Age=0'];
  if (secureCookies) attrs.push('Secure');
  return attrs.join('; ');
}

/** Parse a Cookie header into a plain object. Malformed pairs are skipped, not fatal. */
function parseCookies(header) {
  const jar = Object.create(null);
  if (typeof header !== 'string' || header.length === 0) return jar;
  for (const pair of header.split(';')) {
    const eq = pair.indexOf('=');
    if (eq <= 0) continue;
    const name = pair.slice(0, eq).trim();
    let value = pair.slice(eq + 1).trim();
    try {
      value = decodeURIComponent(value);
    } catch {
      // A value that is not valid percent-encoding is not going to match a token
      // either way; use it as-is rather than failing the whole request.
    }
    jar[name] = value;
  }
  return jar;
}

/** The session token from a Cookie header, or null. */
function readToken(cookieHeader) {
  const token = parseCookies(cookieHeader)[COOKIE_NAME];
  return typeof token === 'string' && token.length > 0 ? token : null;
}

module.exports = { COOKIE_NAME, hashToken, createSession, sessionCookie, expiredCookie, parseCookies, readToken };
